try:
    print(a)
except Exception as erro:
    print('Ocorreu um erro!', erro)